# Generated by Django 4.0.3 on 2022-07-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('path', models.CharField(default='', max_length=100)),
                ('format', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Health_Sensing_doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(default='', max_length=100)),
                ('format', models.CharField(default='', max_length=10)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('is_secret', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Python_doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(default='', max_length=100)),
                ('format', models.CharField(default='', max_length=10)),
                ('order_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Python_module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(default='', max_length=100)),
                ('format', models.CharField(default='', max_length=10)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('is_secret', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
