# Generated by Django 4.0.3 on 2022-07-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HS_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware_doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(default='', max_length=100)),
                ('format', models.CharField(default='', max_length=10)),
                ('order_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
