# Generated by Django 4.1.1 on 2022-11-20 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HS_server', '0004_hwte_station_doc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hardware_doc',
            new_name='College_doc',
        ),
    ]
