# Generated by Django 4.0.3 on 2022-08-17 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_contact_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='internal_port',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='internal_server_port',
        ),
    ]
