# Generated by Django 4.0.3 on 2022-08-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_contact_internal_port_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='cookie',
        ),
        migrations.AddField(
            model_name='contact',
            name='internal_port',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='internal_server_port',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_delete',
            field=models.BinaryField(blank=True, default=b'\x00', null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_online',
            field=models.BinaryField(blank=True, default=b'\x00', null=True),
        ),
    ]
