# Generated by Django 4.0.3 on 2022-08-19 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_remove_contact_cookie_contact_internal_port_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='internal_port',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='internal_server_port',
        ),
    ]
