# Generated by Django 4.1.1 on 2022-09-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallpaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(default='', max_length=100)),
                ('img_format', models.CharField(default='', max_length=10)),
                ('img_type', models.CharField(default='', max_length=10)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('is_secret', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
